package sqlite
import("context";"testing";"github.com/vance1852/hazard-response-control-plane/internal/audit";"github.com/vance1852/hazard-response-control-plane/internal/dispatch")
func TestStage2DeploymentReleaseRollsBackWhenAuditFails(t *testing.T){store:=openTestStore(t);ctx:=context.Background();now:=testClock().Now();sqls:=[]string{
`INSERT INTO regions(id,code,name,timezone,active,created_at,updated_at)VALUES('r24','R24','R24','UTC',1,'2026-08-24T08:00:00Z','2026-08-24T08:00:00Z')`,
`INSERT INTO users(id,region_id,username,password_hash,display_name,role,active,version,created_at,updated_at)VALUES('u24','r24','u24','hash','U24','commander',1,1,'2026-08-24T08:00:00Z','2026-08-24T08:00:00Z')`,
`INSERT INTO incidents(id,region_id,external_ref,hazard_type,title,severity,status,command_level,summary,occurred_at,version,created_by,created_at,updated_at)VALUES('i24','r24','e24','landslide','Slide',3,'active','local','s','2026-08-24T08:00:00Z',1,'u24','2026-08-24T08:00:00Z','2026-08-24T08:00:00Z')`,
`INSERT INTO field_units(id,region_id,call_sign,unit_type,capability_json,status,operator_id,version,created_at,updated_at)VALUES('unit24','r24','UNIT24','rescue','[]','deployed','u24',5,'2026-08-24T08:00:00Z','2026-08-24T08:00:00Z')`,
`INSERT INTO resource_requests(id,incident_id,requested_type,required_capability,quantity,priority,status,needed_by,version,created_by,created_at,updated_at)VALUES('req24','i24','rescue','search',1,4,'allocated','2026-08-24T15:00:00Z',3,'u24','2026-08-24T08:00:00Z','2026-08-24T08:00:00Z')`,
`INSERT INTO deployments(id,request_id,unit_id,incident_id,status,assigned_by,arrived_at,version,created_at,updated_at)VALUES('dep24','req24','unit24','i24','on_scene','u24','2026-08-24T10:00:00Z',2,'2026-08-24T08:00:00Z','2026-08-24T10:00:00Z')`};for _,q:=range sqls{if _,err:=store.DB().Exec(q);err!=nil{t.Fatal(err)}};if _,err:=store.DB().Exec(`CREATE TRIGGER reject_r24_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'audit unavailable');END;`);err!=nil{t.Fatal(err)};event,_:=audit.New("u24","deployment.transition","deployment","dep24","request-r24",audit.OutcomeSucceeded,nil,now);if _,_,err:=store.TransitionDeployment(ctx,"dep24",2,dispatch.DeploymentReleased,"u24",now,event);err==nil{t.Fatal("release succeeded while audit failed")};var dep,unit,request string;store.DB().QueryRow(`SELECT status FROM deployments WHERE id='dep24'`).Scan(&dep);store.DB().QueryRow(`SELECT status FROM field_units WHERE id='unit24'`).Scan(&unit);store.DB().QueryRow(`SELECT status FROM resource_requests WHERE id='req24'`).Scan(&request);if dep!="on_scene"||unit!="deployed"||request!="allocated"{t.Fatalf("failed release leaked deployment=%s unit=%s request=%s",dep,unit,request)};store.DB().Exec(`DROP TRIGGER reject_r24_audit`);released,returned,err:=store.TransitionDeployment(ctx,"dep24",2,dispatch.DeploymentReleased,"u24",now,event);if err!=nil{t.Fatalf("release retry: %v",err)};if released.Status!=dispatch.DeploymentReleased||returned==nil||returned.Status!=dispatch.UnitAvailable{t.Fatalf("release result=%s unit=%#v",released.Status,returned)}}
